---
deployment:
  tasks:
    - name: Pull Latest Changes
      command: git pull origin main

    - name: Install Composer Dependencies
      command: composer install --no-dev --optimize-autoloader

    - name: Set Permissions
      command: |
        chmod -R 775 storage bootstrap/cache
        chown -R $USER:$USER storage bootstrap/cache

    - name: Ensure .env Exists
      command: |
        if [ ! -f .env ]; then
          cp .env.example .env
        fi

    - name: Generate Application Key (if missing)
      command: |
        if ! grep -q "APP_KEY=" .env || [ "$(grep 'APP_KEY=' .env | cut -d '=' -f2)" = "" ]; then
          php artisan key:generate --force
        fi

    - name: Run Migrations
      command: php artisan migrate --force

    - name: Clear Cache and Optimize
      command: |
        php artisan cache:clear
        php artisan config:clear
        php artisan config:cache
        php artisan route:cache

    - name: Restart Queue Workers
      command: php artisan queue:restart
