---
deployment:
  tasks:
    - name: Change to Project Directory
      command: cd artal

    - name: Pull Latest Changes
      command: |
        cd artal && git pull origin main

    - name: Install Composer Dependencies
      command: |
        cd artal && composer install --no-dev --optimize-autoloader

    - name: Set Permissions
      command: |
        cd artal && chmod -R 775 storage bootstrap/cache
        cd artal && chown -R $USER:$USER storage bootstrap/cache

    - name: Ensure .env Exists
      command: |
        cd artal && if [ ! -f .env ]; then cp .env.example .env; fi

    - name: Generate Application Key (if missing)
      command: |
        cd artal && if ! grep -q "APP_KEY=" .env || [ "$(grep 'APP_KEY=' .env | cut -d '=' -f2)" = "" ]; then
          php artisan key:generate --force
        fi

    - name: Run Migrations
      command: cd artal && php artisan migrate --force

    - name: Clear Cache and Optimize
      command: |
        cd artal && php artisan cache:clear
        cd artal && php artisan config:clear
        cd artal && php artisan config:cache
        cd artal && php artisan route:cache

    - name: Restart Queue Workers
      command: cd artal && php artisan queue:restart
